//! The templates compiled into the binary.
//!
//! `assets/templates/<name>/…` is walked by [`build.rs`] and turned into a
//! static table of `include_bytes!`. Adding a template is dropping a directory
//! there — no list to update, and no risk of a file that exists on disk but was
//! forgotten in a hand-written array.
//!
//! These exist so `senclaw create` has no hard network dependency. The git repo
//! is the source of truth and always wins when it is reachable; this is the
//! copy that keeps the command working when it is not.

/// One embedded file. Mirrors [`super::source::TemplateFile`] with borrowed
/// data — the bytes live in the binary's rodata, not the heap.
#[derive(Debug, Clone, Copy)]
pub struct BundledFile {
    /// Path relative to the template root, `/`-separated.
    pub rel: &'static str,
    pub bytes: &'static [u8],
    pub executable: bool,
}

// Generated by build.rs: `static BUNDLED: &[(&str, &[BundledFile])]`.
include!(concat!(env!("OUT_DIR"), "/bundled_templates.rs"));

/// The files of one bundled template, or `None` when there is no such template.
pub fn get(name: &str) -> Option<&'static [BundledFile]> {
    BUNDLED
        .iter()
        .find(|(n, _)| *n == name)
        .map(|(_, files)| *files)
}

/// Every bundled template name, sorted.
pub fn names() -> Vec<&'static str> {
    let mut v: Vec<&'static str> = BUNDLED.iter().map(|(n, _)| *n).collect();
    v.sort_unstable();
    v
}

/// The bundled `template.json` for a template, unparsed.
pub fn spec_json(name: &str) -> Option<&'static str> {
    let files = get(name)?;
    files
        .iter()
        .find(|f| f.rel == "template.json")
        .and_then(|f| std::str::from_utf8(f.bytes).ok())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::scaffold::spec::{Kind, Lang, TemplateSpec};

    /// The four languages the CLI advertises must all be reachable offline —
    /// otherwise `--lang go` works on a connected machine and fails on a plane.
    #[test]
    fn every_advertised_language_has_a_bundled_template() {
        for lang in Lang::ALL {
            let name = lang.template_name();
            assert!(
                get(&name).is_some(),
                "thiếu template đi kèm {name:?}; có: {:?}",
                names()
            );
        }
        assert!(get("skill").is_some());
        assert!(get("sub-agent").is_some());
    }

    #[test]
    fn every_bundled_template_declares_a_valid_spec() {
        for name in names() {
            let raw = spec_json(name)
                .unwrap_or_else(|| panic!("template đi kèm {name:?} thiếu template.json"));
            let spec = TemplateSpec::parse(raw, name)
                .unwrap_or_else(|e| panic!("template.json của {name:?} hỏng: {e}"));
            assert_eq!(spec.name, name, "trường name phải khớp tên thư mục");
            assert!(
                spec.kind.is_some(),
                "{name:?} phải khai báo kind (app|skill|sub-agent)"
            );
            assert!(
                spec.description.is_some(),
                "{name:?} phải có description — nó là dòng `senclaw create list` in ra"
            );
        }
    }

    /// The daemon's bridge request struct
    /// ([`crate::gateway::ui_server`] `SpaceAppBridgeBody`) requires a field
    /// named `action`. A template that sends `capability` instead gets a 422
    /// from axum's JSON extractor before any handler runs — and because the
    /// templates surface that as a tidy `isError` block, it looks exactly like
    /// the expected "no daemon running" degradation. It shipped once; this is
    /// what stops it shipping again.
    #[test]
    fn app_templates_call_the_bridge_with_the_field_the_daemon_requires() {
        for name in names() {
            for f in get(name).unwrap() {
                let Ok(text) = std::str::from_utf8(f.bytes) else {
                    continue;
                };
                if !text.contains("/bridge") {
                    continue;
                }
                assert!(
                    text.contains("\"action\"") || text.contains("action:"),
                    "{name}/{} gọi /bridge nhưng không gửi trường `action`",
                    f.rel
                );
                // The exact wrong spelling, as a request key. Prose mentioning
                // the word is fine; `"capability":` / `capability:` is not.
                for wrong in ["\"capability\":", "capability:", "'capability':"] {
                    assert!(
                        !text.contains(wrong),
                        "{name}/{} gửi {wrong} — daemon cần `action`, body này bị 422",
                        f.rel
                    );
                }
            }
        }
    }

    /// The daemon answers a *failed* completion with HTTP 200 and
    /// `{"status":"error"}`. A template that only checks the HTTP status turns
    /// a provider outage into a successful empty summary.
    #[test]
    fn app_templates_notice_an_error_status_on_a_200() {
        for name in names() {
            let Some(files) = get(name) else { continue };
            let calls_bridge = files.iter().any(|f| {
                std::str::from_utf8(f.bytes)
                    .map(|t| t.contains("/bridge"))
                    .unwrap_or(false)
            });
            if !calls_bridge {
                continue;
            }
            let handles = files.iter().any(|f| {
                std::str::from_utf8(f.bytes)
                    .map(|t| t.contains("\"error\"") || t.contains("'error'"))
                    .unwrap_or(false)
            });
            assert!(handles, "{name} không xử lý status==\"error\" từ bridge");
        }
    }

    /// The payload is what gets written, so an app template with no manifest
    /// produces a directory the daemon will never load.
    #[test]
    fn app_templates_carry_a_manifest_and_skills_carry_a_skill_md() {
        for name in names() {
            let raw = spec_json(name).unwrap();
            let spec = TemplateSpec::parse(raw, name).unwrap();
            let files = get(name).unwrap();
            // `ends_with`, not `==`: a template may keep its payload under
            // `files/` so its own README is not copied into the new project.
            let has = |rel: &str| files.iter().any(|f| f.rel.ends_with(rel));
            match spec.kind_or_default() {
                Kind::App => assert!(has("senclaw-manifest.json"), "{name} thiếu manifest"),
                Kind::Skill => assert!(has("SKILL.md"), "{name} thiếu SKILL.md"),
                Kind::SubAgent => assert!(
                    files.iter().any(|f| f.rel.ends_with(".md")),
                    "{name} thiếu file .md"
                ),
            }
        }
    }
}
