//! Bake git + build metadata into the binary at compile time.
//!
//! `senclaw version` (and clap's `--version`) report these. Everything is
//! best-effort: building from a source tarball with no `.git`, or on a
//! machine without git, must still compile — the fields just read "unknown".
//!
//! Also embeds `assets/templates/` for `senclaw create` (see
//! [`emit_bundled_templates`]) and `assets/patterns/` + `assets/strategies/`
//! for Zen Patterns (see [`emit_bundled_patterns`]).

use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::{SystemTime, UNIX_EPOCH};

fn git(args: &[&str]) -> Option<String> {
    let out = Command::new("git").args(args).output().ok()?;
    if !out.status.success() {
        return None;
    }
    let s = String::from_utf8_lossy(&out.stdout).trim().to_string();
    (!s.is_empty()).then_some(s)
}

fn main() {
    // `--always` keeps this working on shallow CI checkouts that fetched no
    // tags: the describe degrades to the bare short hash instead of failing.
    let describe = git(&["describe", "--tags", "--always", "--dirty=+"])
        .unwrap_or_else(|| "unknown".into());
    let hash = git(&["rev-parse", "--short=12", "HEAD"]).unwrap_or_else(|| "unknown".into());

    let epoch = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);

    // The build-script TARGET env var is the triple being compiled FOR —
    // matches the release asset naming (aarch64-apple-darwin, …).
    let target = std::env::var("TARGET").unwrap_or_else(|_| "unknown".into());

    println!("cargo:rustc-env=SENCLAW_GIT_DESCRIBE={describe}");
    println!("cargo:rustc-env=SENCLAW_GIT_HASH={hash}");
    println!("cargo:rustc-env=SENCLAW_BUILD_EPOCH={epoch}");
    println!("cargo:rustc-env=SENCLAW_BUILD_TARGET={target}");

    // Recompile the metadata when the checked-out commit moves. (Deliberately
    // NOT watching the index: that would rebuild on every `git add`.)
    println!("cargo:rerun-if-changed=.git/HEAD");
    println!("cargo:rerun-if-changed=.git/refs");

    emit_bundled_templates();
    emit_bundled_patterns();
    emit_bundled_skills();
    emit_bundled_specs();
}

/// Turn `skills/<name>/…` into a static table the daemon can unpack itself.
///
/// Without this the builtin skills only exist as a *path*: `Paths::
/// bundled_skills_dir` falls back to `CARGO_MANIFEST_DIR/skills`, which is the
/// build machine's source tree. It resolves for a developer running out of the
/// checkout and for nobody else — a downloaded release binary looks for a
/// directory that does not exist on the user's disk, finds nothing, and serves
/// zero builtin skills. The failure is silent: `pattern`, `web-research`,
/// `agent-browser` and the rest simply never appear in the registry.
///
/// Walked rather than hand-listed for the same reason the templates are: adding
/// a skill must be dropping a directory in, not remembering to edit a list.
fn emit_bundled_skills() {
    let root = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap()).join("skills");
    println!("cargo:rerun-if-changed=skills");

    let mut skills: Vec<(String, Vec<(String, PathBuf, bool)>)> = Vec::new();
    if root.is_dir() {
        let mut dirs: Vec<PathBuf> = std::fs::read_dir(&root)
            .unwrap()
            .flatten()
            .map(|e| e.path())
            .filter(|p| p.is_dir())
            .collect();
        dirs.sort();
        for dir in dirs {
            let name = dir.file_name().unwrap().to_string_lossy().to_string();
            if name.starts_with('.') {
                continue;
            }
            let mut files = Vec::new();
            collect(&dir, &dir, &mut files);
            files.sort_by(|a, b| a.0.cmp(&b.0));
            // A directory with no SKILL.md is not a skill; shipping it would
            // put a permanently unparseable entry in every user's registry.
            if files.iter().any(|(rel, _, _)| rel == "SKILL.md") {
                skills.push((name, files));
            }
        }
    }

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit.\n");
    out.push_str("static BUNDLED_SKILLS: &[(&str, &[BundledSkillFile])] = &[\n");
    for (name, files) in &skills {
        let _ = writeln!(out, "    ({name:?}, &[");
        for (rel, path, exec) in files {
            let _ = writeln!(
                out,
                "        BundledSkillFile {{ rel: {rel:?}, bytes: include_bytes!({}), executable: {exec} }},",
                escape_path(path)
            );
        }
        out.push_str("    ]),\n");
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("bundled_skills.rs");
    std::fs::write(dest, out).unwrap();
}

/// Turn `assets/templates/<name>/…` into a static table `senclaw create` can
/// render without a network round trip.
///
/// Written as generated `include_bytes!` calls rather than a hand-maintained
/// array so that adding a template is dropping a directory in — the failure
/// mode of the alternative is a file that exists in the repo, is missing from
/// the binary, and nobody notices until a user is offline.
fn emit_bundled_templates() {
    let root = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap()).join("assets/templates");
    // One directive covers edits, additions AND deletions anywhere underneath:
    // cargo resolves a directory path with a recursive mtime walk, and a file
    // added or removed bumps its parent directory's own mtime — so this also
    // catches a file restored from a tarball with a backdated timestamp.
    // (Measured, not assumed.) The cost is that the walk does not know about
    // `collect`'s skip list below: building a template *in place* to check it
    // still compiles leaves a `target/` here that every later senclaw build
    // walks. Generate a copy with `senclaw create` and build that instead.
    println!("cargo:rerun-if-changed=assets/templates");

    let mut templates: Vec<(String, Vec<(String, PathBuf, bool)>)> = Vec::new();
    if root.is_dir() {
        let mut dirs: Vec<PathBuf> = std::fs::read_dir(&root)
            .unwrap()
            .flatten()
            .map(|e| e.path())
            .filter(|p| p.is_dir())
            .collect();
        dirs.sort();
        for dir in dirs {
            let name = dir.file_name().unwrap().to_string_lossy().to_string();
            if name.starts_with('.') {
                continue;
            }
            let mut files = Vec::new();
            collect(&dir, &dir, &mut files);
            files.sort_by(|a, b| a.0.cmp(&b.0));
            if !files.is_empty() {
                templates.push((name, files));
            }
        }
    }

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit.\n");
    out.push_str("static BUNDLED: &[(&str, &[BundledFile])] = &[\n");
    for (name, files) in &templates {
        let _ = writeln!(out, "    ({name:?}, &[");
        for (rel, path, exec) in files {
            let _ = writeln!(
                out,
                "        BundledFile {{ rel: {rel:?}, bytes: include_bytes!({}), executable: {exec} }},",
                escape_path(path)
            );
        }
        out.push_str("    ]),\n");
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("bundled_templates.rs");
    std::fs::write(dest, out).unwrap();
}

/// Turn `assets/patterns/<name>/system.md` and `assets/strategies/*.json` into
/// static tables the daemon can install with no network at all.
///
/// Walked rather than hand-listed for the same reason the templates are: the
/// library is 261 directories and re-vendoring it replaces them wholesale, so
/// a list would be wrong within one update — and wrong in the silent direction,
/// where a file exists in the repo, is missing from the binary, and nobody
/// notices until a user is offline.
fn emit_bundled_patterns() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    println!("cargo:rerun-if-changed=assets/patterns");
    println!("cargo:rerun-if-changed=assets/strategies");

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit.\n");

    // ── patterns ─────────────────────────────────────────────────────────
    let root = manifest.join("assets/patterns");
    let mut dirs: Vec<PathBuf> = std::fs::read_dir(&root)
        .map(|rd| {
            rd.flatten()
                .map(|e| e.path())
                .filter(|p| p.is_dir() && p.join("system.md").is_file())
                .collect()
        })
        .unwrap_or_default();
    dirs.sort();

    out.push_str("static BUNDLED_PATTERNS: &[BundledPattern] = &[\n");
    for dir in &dirs {
        let name = dir.file_name().unwrap().to_string_lossy().to_string();
        if name.starts_with('.') {
            continue;
        }
        let user = dir.join("user.md");
        let user_lit = if user.is_file() {
            format!("Some(include_str!({}))", escape_path(&user))
        } else {
            "None".to_string()
        };
        let _ = writeln!(
            out,
            "    BundledPattern {{ name: {name:?}, system: include_str!({}), user: {user_lit} }},",
            escape_path(&dir.join("system.md"))
        );
    }
    out.push_str("];\n");

    // ── strategies ───────────────────────────────────────────────────────
    let sroot = manifest.join("assets/strategies");
    let mut files: Vec<PathBuf> = std::fs::read_dir(&sroot)
        .map(|rd| {
            rd.flatten()
                .map(|e| e.path())
                .filter(|p| p.extension().map(|e| e == "json").unwrap_or(false))
                .collect()
        })
        .unwrap_or_default();
    files.sort();

    out.push_str("static BUNDLED_STRATEGIES: &[(&str, &str)] = &[\n");
    for f in &files {
        let name = f.file_stem().unwrap().to_string_lossy().to_string();
        let _ = writeln!(out, "    ({name:?}, include_str!({})),", escape_path(f));
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("bundled_patterns.rs");
    std::fs::write(dest, out).unwrap();
}

/// Embed `assets/specs/*.json` (the control-plane spec registry, §5/§12) the
/// same way [`emit_bundled_patterns`] embeds the pattern library: walked, not
/// hand-listed, so dropping a new spec file in is the whole change. Each
/// entry keeps its raw text — `control_plane::registry` parses and validates
/// it at load time, not here, so a spec mistake is a registry error at
/// startup rather than a build failure a contributor cannot see the cause of.
fn emit_bundled_specs() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    println!("cargo:rerun-if-changed=assets/specs");

    let root = manifest.join("assets/specs");
    let mut files: Vec<PathBuf> = std::fs::read_dir(&root)
        .map(|rd| {
            rd.flatten()
                .map(|e| e.path())
                .filter(|p| p.extension().map(|e| e == "json").unwrap_or(false))
                .collect()
        })
        .unwrap_or_default();
    files.sort();

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit.\n");
    out.push_str("static BUNDLED_SPECS: &[BundledSpec] = &[\n");
    for f in &files {
        let id = f.file_stem().unwrap().to_string_lossy().to_string();
        let _ = writeln!(
            out,
            "    BundledSpec {{ id: {id:?}, json: include_str!({}) }},",
            escape_path(f)
        );
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("bundled_specs.rs");
    std::fs::write(dest, out).unwrap();
}

fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf, bool)>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().to_string();
        // scaffold::spec::ALWAYS_IGNORED minus `template.json`, which is kept
        // deliberately — scaffold::bundled reads the spec out of the embedded
        // table, and strips it from the payload at render time instead.
        // `.senclaw` is here because running a template app in place writes
        // `<app>/.senclaw/mcp-tools.json`, and a stale tool cache has no
        // business inside the shipped binary.
        if matches!(
            name.as_str(),
            ".git"
                | ".DS_Store"
                | "node_modules"
                | "target"
                | "__pycache__"
                | ".venv"
                | "dist"
                | ".senclaw"
        ) {
            continue;
        }
        if path.is_dir() {
            collect(root, &path, out);
        } else if path.is_file() {
            let rel = path
                .strip_prefix(root)
                .unwrap()
                .to_string_lossy()
                .replace('\\', "/");
            out.push((rel, path.clone(), is_executable(&path)));
        }
    }
}

#[cfg(unix)]
fn is_executable(path: &Path) -> bool {
    use std::os::unix::fs::PermissionsExt;
    std::fs::metadata(path)
        .map(|m| m.permissions().mode() & 0o111 != 0)
        .unwrap_or(false)
}

#[cfg(not(unix))]
fn is_executable(path: &Path) -> bool {
    path.extension().map(|e| e == "sh").unwrap_or(false)
}

/// `include_bytes!` needs a string literal; on Windows the path separators must
/// survive Rust's escape rules.
fn escape_path(p: &Path) -> String {
    format!("{:?}", p.to_string_lossy())
}
