//! Persistence for fired space-event reminders and queries for the
//! "pending upcoming" preview. Today the `EventNotifier` only broadcasts
//! a live `space:event:reminder` WS frame — if the user wasn't connected,
//! the reminder is gone. Here we log every fire so reload still surfaces
//! it, and we also expose a forward-looking query that lists events whose
//! reminders are due soon but haven't been generated yet.

use anyhow::Result;
use rusqlite::{params, Connection, OptionalExtension};

#[derive(Debug, Clone)]
pub struct StoredEventNotification {
    pub id: String,
    pub event_id: String,
    pub title: String,
    /// `start_at` of the source event, in epoch ms. Mirrored here so the
    /// notification row is self-contained for the Sidebar.
    pub start_at: i64,
    pub kind: String,
    pub fired_at: i64,
    /// Difference between when the reminder *should* have fired and when
    /// it actually did. Non-zero when the daemon was down or sleeping
    /// past the trigger window.
    pub delayed_ms: i64,
    pub read_at: Option<i64>,
}

/// Forward-looking view of an event whose reminder hasn't fired yet but
/// will, soon. Surfaced in the UI so the user can preview what's coming
/// even before the EventNotifier polls again.
#[derive(Debug, Clone)]
pub struct PendingEventReminder {
    pub event_id: String,
    pub title: String,
    pub start_at: i64,
    pub reminder_min: i64,
    /// `start_at - reminder_min*60_000` — the moment the reminder *would*
    /// be generated by the next EventNotifier tick.
    pub trigger_at: i64,
}

pub fn insert_event_notification_conn(
    conn: &Connection,
    notif: &StoredEventNotification,
) -> Result<()> {
    conn.execute(
        r#"
        INSERT INTO event_notifications
          (id, event_id, title, start_at, kind, fired_at, delayed_ms, read_at)
        VALUES (?1,?2,?3,?4,?5,?6,?7,?8)
        "#,
        params![
            notif.id,
            notif.event_id,
            notif.title,
            notif.start_at,
            notif.kind,
            notif.fired_at,
            notif.delayed_ms,
            notif.read_at,
        ],
    )?;
    Ok(())
}

impl super::Db {
    pub fn insert_event_notification(&self, notif: &StoredEventNotification) -> Result<()> {
        self.with_conn(|c| insert_event_notification_conn(c, notif))
    }

    /// Most-recent fired notifications. Returned newest-first so the UI
    /// can render directly without a re-sort.
    pub fn list_event_notifications(
        &self,
        limit: Option<u32>,
    ) -> Result<Vec<StoredEventNotification>> {
        self.with_conn(|c| {
            let lim = limit.unwrap_or(100) as i64;
            let mut stmt = c.prepare(
                "SELECT id, event_id, title, start_at, kind, fired_at, delayed_ms, read_at
                 FROM event_notifications
                 ORDER BY fired_at DESC, id DESC
                 LIMIT ?1",
            )?;
            let rows: Vec<StoredEventNotification> = stmt
                .query_map(params![lim], |r| {
                    Ok(StoredEventNotification {
                        id: r.get(0)?,
                        event_id: r.get(1)?,
                        title: r.get(2)?,
                        start_at: r.get(3)?,
                        kind: r.get(4)?,
                        fired_at: r.get(5)?,
                        delayed_ms: r.get(6)?,
                        read_at: r.get(7)?,
                    })
                })?
                .collect::<rusqlite::Result<Vec<_>>>()?;
            Ok(rows)
        })
    }

    pub fn mark_event_notification_read(&self, id: &str, read_at: i64) -> Result<usize> {
        self.with_conn(|c| {
            Ok(c.execute(
                "UPDATE event_notifications SET read_at = ?2 WHERE id = ?1",
                params![id, read_at],
            )?)
        })
    }

    pub fn get_event_notification(&self, id: &str) -> Result<Option<StoredEventNotification>> {
        self.with_conn(|c| {
            Ok(c.query_row(
                "SELECT id, event_id, title, start_at, kind, fired_at, delayed_ms, read_at
                 FROM event_notifications WHERE id = ?1",
                params![id],
                |r| {
                    Ok(StoredEventNotification {
                        id: r.get(0)?,
                        event_id: r.get(1)?,
                        title: r.get(2)?,
                        start_at: r.get(3)?,
                        kind: r.get(4)?,
                        fired_at: r.get(5)?,
                        delayed_ms: r.get(6)?,
                        read_at: r.get(7)?,
                    })
                },
            )
            .optional()?)
        })
    }

    /// Events whose reminder will fire within `now_ms..=now_ms + window_ms`
    /// but for which `reminder_sent_at` is still NULL. Surfaced as a
    /// "coming up" preview so the user sees pending items before the
    /// notifier loop actually wakes.
    pub fn list_pending_event_reminders(
        &self,
        now_ms: i64,
        window_ms: i64,
    ) -> Result<Vec<PendingEventReminder>> {
        self.with_conn(|c| {
            let cutoff = now_ms + window_ms;
            let mut stmt = c.prepare(
                "SELECT id, title, start_at, reminder_min,
                        (start_at - reminder_min * 60000) AS trigger_at
                 FROM space_events
                 WHERE deleted_at IS NULL
                   AND reminder_min IS NOT NULL
                   AND reminder_sent_at IS NULL
                   AND status IN ('upcoming','ongoing')
                   AND end_at > ?1
                   AND (start_at - reminder_min * 60000) <= ?2
                 ORDER BY trigger_at ASC",
            )?;
            let rows: Vec<PendingEventReminder> = stmt
                .query_map(params![now_ms, cutoff], |r| {
                    Ok(PendingEventReminder {
                        event_id: r.get(0)?,
                        title: r.get(1)?,
                        start_at: r.get(2)?,
                        reminder_min: r.get(3)?,
                        trigger_at: r.get(4)?,
                    })
                })?
                .collect::<rusqlite::Result<Vec<_>>>()?;
            Ok(rows)
        })
    }
}

#[cfg(test)]
mod tests {
    use super::StoredEventNotification;
    use crate::config::Config;
    use crate::db::Db;
    use rusqlite::params;

    fn make(id: &str, event_id: &str, fired_at: i64, delayed_ms: i64) -> StoredEventNotification {
        StoredEventNotification {
            id: id.into(),
            event_id: event_id.into(),
            title: format!("Event {event_id}"),
            start_at: fired_at + 5 * 60_000,
            kind: "reminder".into(),
            fired_at,
            delayed_ms,
            read_at: None,
        }
    }

    #[test]
    fn list_orders_newest_first_and_supports_limit() {
        let cfg = Config::from_env();
        let db = Db::open_in_memory(&cfg).expect("open db");

        db.insert_event_notification(&make("n1", "e1", 1_000, 0))
            .unwrap();
        db.insert_event_notification(&make("n2", "e2", 2_000, 0))
            .unwrap();
        db.insert_event_notification(&make("n3", "e3", 3_000, 5_000))
            .unwrap();

        let rows = db.list_event_notifications(None).unwrap();
        assert_eq!(rows.len(), 3);
        assert_eq!(rows[0].id, "n3");
        assert_eq!(rows[2].id, "n1");

        let two = db.list_event_notifications(Some(2)).unwrap();
        assert_eq!(two.len(), 2);
        assert_eq!(two[0].id, "n3");
        assert_eq!(two[1].id, "n2");
    }

    #[test]
    fn mark_read_updates_row() {
        let cfg = Config::from_env();
        let db = Db::open_in_memory(&cfg).expect("open db");

        db.insert_event_notification(&make("n1", "e1", 1_000, 0))
            .unwrap();
        assert_eq!(db.mark_event_notification_read("n1", 9_000).unwrap(), 1);
        let got = db.get_event_notification("n1").unwrap().unwrap();
        assert_eq!(got.read_at, Some(9_000));
    }

    #[test]
    fn pending_reminders_only_returns_in_window_and_unfired() {
        let cfg = Config::from_env();
        let db = Db::open_in_memory(&cfg).expect("open db");
        let now = chrono::Utc::now().timestamp_millis();

        db.with_conn(|conn| {
            // (a) due in 3 min, reminder 5 min → trigger 2 min ago → IN window
            insert_event(
                conn,
                "e-a",
                "Within window",
                now + 3 * 60_000,
                now + 30 * 60_000,
                Some(5),
                None,
                false,
            );
            // (b) due in 60 min, reminder 5 min → trigger in 55 min → OUTSIDE 10-min window
            insert_event(
                conn,
                "e-b",
                "Far future",
                now + 60 * 60_000,
                now + 90 * 60_000,
                Some(5),
                None,
                false,
            );
            // (c) reminder already sent → should NOT appear
            insert_event(
                conn,
                "e-c",
                "Already sent",
                now + 3 * 60_000,
                now + 30 * 60_000,
                Some(5),
                None,
                true,
            );
            // (d) no reminder_min set → should NOT appear
            insert_event(
                conn,
                "e-d",
                "No reminder",
                now + 3 * 60_000,
                now + 30 * 60_000,
                None,
                None,
                false,
            );
            Ok(())
        })
        .unwrap();

        let pending = db.list_pending_event_reminders(now, 10 * 60_000).unwrap();
        let ids: Vec<&str> = pending.iter().map(|p| p.event_id.as_str()).collect();
        assert!(ids.contains(&"e-a"), "expected e-a in pending, got {ids:?}");
        assert!(!ids.contains(&"e-b"));
        assert!(!ids.contains(&"e-c"));
        assert!(!ids.contains(&"e-d"));
    }

    fn insert_event(
        conn: &rusqlite::Connection,
        id: &str,
        title: &str,
        start_ms: i64,
        end_ms: i64,
        reminder_min: Option<i64>,
        renotify_min: Option<i64>,
        already_sent: bool,
    ) {
        let now = chrono::Utc::now().timestamp_millis();
        conn.execute(
            "INSERT INTO space_events
             (id, title, start_at, end_at, reminder_min, renotify_min, reminder_sent_at, created_at, updated_at)
             VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?8)",
            params![id, title, start_ms, end_ms, reminder_min, renotify_min,
                    if already_sent { Some(now) } else { None }, now],
        )
        .unwrap();
    }
}
